#!/bin/sh

# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

out_header="./inc_data.h"
out_file="./data.bin"

rm -f $out_header
rm -f $out_file

if [ -z $1 ]; then
	echo "Failed to find file"
	exit 1
fi

touch $out_header
touch $out_file

echo "#ifndef INC_DATA_H" >> $out_header
echo "#define INC_DATA_H" >> $out_header
echo >> $out_header
echo "/* Automatically generated by data_cat.sh */" >> $out_header

echo "enum INC_DATA_VALUE {" >> $out_header

for i in $(cat $1); do
	pos=$(wc -c < $out_file)
	size=$(wc -c < $i)

	cat $i >> $out_file
	name_upper=$(echo $i | sed "s/\//_/g; s/\./_/g; s/[a-z]/\U&/g")

	echo "    ${name_upper}_POS = $pos," >> $out_header
	echo "    ${name_upper}_SIZE = $size," >> $out_header
	echo >> $out_header
done

echo "    INC_DATA_END" >> $out_header

echo "};" >> $out_header

echo >> $out_header
echo "#endif" >> $out_header
